name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        ip add
        docker run -d --restart unless-stopped --name baota --net=host -v ~/website_data:/www/wwwroot -v ~/mysql_data:/www/server/data -v /vhost:/www/server/panel/vhost docker.cnb.cool/btpanel/btpanel:latest
        docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMGM4MjZiMWUyYzdmZDAxNTlmNDZmZjk4MmY3MzcxMGIiLCJ0IjoiMzZkZTVlNmQtZGM3Ni00ZmViLTk4MjYtODU1ZTE5Y2I3MDcwIiwicyI6IlpHTTRPRGMwWTJNdE5tWXhaaTAwWkRRNExUZzNOall0TkRrelltUXpOVFUzT0dKaiJ9
