name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker run -it -v /data:/var/www/html
        docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMGM4MjZiMWUyYzdmZDAxNTlmNDZmZjk4MmY3MzcxMGIiLCJ0IjoiMzZkZTVlNmQtZGM3Ni00ZmViLTk4MjYtODU1ZTE5Y2I3MDcwIiwicyI6IlpHTTRPRGMwWTJNdE5tWXhaaTAwWkRRNExUZzNOall0TkRrelltUXpOVFUzT0dKaiJ9
