name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        ip add
        docker pull baotaorg/bt
        docker run -d -p 8888:8888 --name baota_container baotaorg/bt
        docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMGM4MjZiMWUyYzdmZDAxNTlmNDZmZjk4MmY3MzcxMGIiLCJ0IjoiMzZkZTVlNmQtZGM3Ni00ZmViLTk4MjYtODU1ZTE5Y2I3MDcwIiwicyI6IlpHTTRPRGMwWTJNdE5tWXhaaTAwWkRRNExUZzNOall0TkRrelltUXpOVFUzT0dKaiJ9
